apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogdb
  labels:
    app: catalogdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogdb
  template:
    metadata:
      name: catalogdb
      labels:
        app: catalogdb
    spec:
      containers:
        - name: catalogdb
          image: mongo
          imagePullPolicy: IfNotPresent
#          env:
#            - name: MONGO_INITDB_ROOT_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  key: mongo-root-username
#                  name: mongo-secret
#            - name: MONGO_INITDB_ROOT_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  key: mongo-root-password
#                  name: mongo-secret
          volumeMounts:
            - mountPath: /data/db
              name: mongo-data
      volumes:
          - name: mongo-data
            persistentVolumeClaim:
              claimName: mongo-data  
      restartPolicy: Always
      