apiVersion: v1
kind: Service
metadata:
  name: catalogdb
spec:
  selector:
    app: catalogdb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 30001
  type: NodePort
  