apiVersion: v1
kind: Service
metadata:
  name: catalogapi-service
spec:
  selector:
    app: catalog-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30003
  type: LoadBalancer
  loadBalancerIP: 172.179.145.95
  
  
  