apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: basketapi
  name: basketapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: basketapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: basketapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: CacheSettings__ConnectionString
              value: basketdb:6379
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq:5672
            - name: GrpcSettings__DiscountUrl
              value: http://discount.api
          image: rahulsahay19/basketapi
          name: basketapi
          ports:
            - containerPort: 80
              protocol: TCP 
      restartPolicy: Always
