apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: basketapi
  name: basketapi
spec:
  ports:
    - name: "9001"
      port: 9001
      targetPort: 80
      nodePort: 30003
  type: NodePort
  selector:
    io.kompose.service: basketapi
