apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: catalogdb
  name: catalogdb
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
      nodePort: 30005
  type: NodePort
  selector:
    io.kompose.service: catalogdb
