apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: catalogapi
  name: catalogapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catalogapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: catalogapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__BrandsCollection
              value: Brands
            - name: DatabaseSettings__CollectionName
              value: Products
            - name: DatabaseSettings__ConnectionString
              value: mongodb://catalogdb:27017
            - name: DatabaseSettings__DatabaseName
              value: CatalogDb
            - name: DatabaseSettings__TypesCollection
              value: Types
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          image: rahulsahay19/catalogapi
          name: catalogapi
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
