apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: discountapi
  name: discountapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discountapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: discountapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DatabaseSettings__ConnectionString
              value: Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=Password@1;
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
          image: rahulsahay19/discountapi
          name: discountapi
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
