apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  ports:
    - name: "9200"
      port: 9200
      targetPort: 9200
      nodePort: 30008
  type: NodePort
  selector:
    io.kompose.service: elasticsearch
