apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ocelotapigw
  name: ocelotapigw
spec:
  ports:
    - name: "9010"
      port: 9010
      targetPort: 80
      nodePort: 30016
  type: NodePort
  selector:
    io.kompose.service: ocelotapigw
