apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orderingapi
  name: orderingapi
spec:
  ports:
    - name: "9003"
      port: 9003
      targetPort: 80
      nodePort: 30012
  type: NodePort
  selector:
    io.kompose.service: orderingapi
