apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orderdb
  name: orderdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderdb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orderdb
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: Suraj1234567
          image: mcr.microsoft.com/mssql/server:2017-latest
          name: orderdb
          ports:
            - containerPort: 1433
              protocol: TCP
      restartPolicy: Always
