apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orderdb
  name: orderdb
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
      nodePort: 30011
  type: NodePort
  selector:
    io.kompose.service: orderdb
