apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: orderingapi
  name: orderingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderingapi
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: orderingapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__OrderingConnectionString
              value: Server=orderdb;Database=OrderDb;User Id=sa;Password=Suraj1234567
            - name: ElasticConfiguration__Uri
              value: http://elasticsearch:9200
            - name: EventBusSettings__HostAddress
              value: amqp://guest:guest@rabbitmq:5672
          image: surajrawat1210/orderingapi
          name: orderingapi
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
