#apiVersion: v1
#kind: Service
#metadata:
#  annotations:
#    kompose.cmd: kompose convert -f docker-compose.yml -f docker-compose.override.yml -o kubernetes
#    kompose.version: 1.34.0 (HEAD)
#  labels:
#    io.kompose.service: portainer
#  name: portainer
#spec:
#  ports:
#    - name: "8080"
#      port: 8080
#      targetPort: 8000
#    - name: "9090"
#      port: 9090
#      targetPort: 9000
#      nodePort: 30014
#  type: NodePort
#  selector:
#    io.kompose.service: portainer
